image: go1.3

git:
  path: github.com/ciarand/bot

env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - go get ./...
  - go get github.com/bradfitz/goimports
  - go get github.com/golang/lint
  - go get code.google.com/p/go.tools/cmd/vet
  - make test
